apiVersion: v1
kind: Service
metadata:
  name: file-service
  namespace: mediasuite
spec:
  type: LoadBalancer
  selector:
    app: file
  ports:
    - name: http
      port: 8090            # External service port
      targetPort: 8080     # Container port
      protocol: TCP

