apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: mediasuite
spec:
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: mediasuite
spec:
  type: LoadBalancer
  selector:
    app: jellyfin
  # In Kubernetes, when a Service has multiple ports, each port must be assigned a unique name, especially when mixing TCP and UDP protocols.
  ports:
  - name: http-tcp
    port: 8096
    protocol: TCP
    targetPort: 8096
  - name: https-tcp
    port: 8920
    protocol: TCP
    targetPort: 8920
  - name: dlna-udp
    port: 1900
    protocol: UDP
    targetPort: 1900
  - name: discovery-udp
    port: 7359
    protocol: UDP
    targetPort: 7359
